/* Generated by Nimrod Compiler v0.9.2 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/claude/Projekte/Nimrod/lib -o /home/claude/Projekte/vanar/src/nimcache/navmFrontend.o /home/claude/Projekte/vanar/src/nimcache/navmFrontend.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>

#include <stdlib.h>

#include <setjmp.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tnavmfrontend97004 tnavmfrontend97004;
typedef struct tnavmbackend91004 tnavmbackend91004;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tshmbuffer91012 tshmbuffer91012;
typedef struct TY97013 TY97013;
typedef struct E_Base E_Base;
typedef struct TSafePoint TSafePoint;
typedef struct tcell38449 tcell38449;
typedef struct tcellseq38465 tcellseq38465;
typedef struct tgcheap40416 tgcheap40416;
typedef struct tcellset38461 tcellset38461;
typedef struct tpagedesc38457 tpagedesc38457;
typedef struct tmemregion22010 tmemregion22010;
typedef struct tsmallchunk21243 tsmallchunk21243;
typedef struct tllchunk22004 tllchunk22004;
typedef struct tbigchunk21245 tbigchunk21245;
typedef struct tintset21218 tintset21218;
typedef struct ttrunk21214 ttrunk21214;
typedef struct tavlnode22008 tavlnode22008;
typedef struct tgcstat40414 tgcstat40414;
typedef struct tbasechunk21241 tbasechunk21241;
typedef struct tfreecell21233 tfreecell21233;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef NimStringDesc* TY94095[1];
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct tshmbuffer91012 {
  TNimObject Sup;
NU8* Pbuffer;
NI Cbuffer;
NIM_BOOL Finit;
};
struct tnavmbackend91004 {
  TNimObject Sup;
NI8 Vd;
NI8 Vr;
tshmbuffer91012 Tcodemem;
NI Ocodemem;
NIM_BOOL Finit;
};
struct tnavmfrontend97004 {
  tnavmbackend91004 Sup;
NIM_BOOL Fdisasm;
NI64 Va;
TY97013* Svmmem;
NI Ovmmem;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct E_Base {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (E_Base* e, void* ClEnv);
void* ClEnv;
} TY10226;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY10226 raiseAction;
};
struct tcell38449 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38465 {
NI Len;
NI Cap;
tcell38449** D;
};
struct tcellset38461 {
NI Counter;
NI Max;
tpagedesc38457* Head;
tpagedesc38457** Data;
};
typedef tsmallchunk21243* TY22022[512];
typedef ttrunk21214* ttrunkbuckets21216[256];
struct tintset21218 {
ttrunkbuckets21216 Data;
};
struct tmemregion22010 {
NI Minlargeobj;
NI Maxlargeobj;
TY22022 Freesmallchunks;
tllchunk22004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21245* Freechunkslist;
tintset21218 Chunkstarts;
tavlnode22008* Root;
tavlnode22008* Deleted;
tavlnode22008* Last;
tavlnode22008* Freeavlnodes;
};
struct tgcstat40414 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40416 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38465 Zct;
tcellseq38465 Decstack;
tcellset38461 Cycleroots;
tcellseq38465 Tempstack;
NI Recgclock;
tmemregion22010 Region;
tgcstat40414 Stat;
};
typedef NI TY21221[8];
struct tpagedesc38457 {
tpagedesc38457* Next;
NI Key;
TY21221 Bits;
};
struct tbasechunk21241 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21243 {
  tbasechunk21241 Sup;
tsmallchunk21243* Next;
tsmallchunk21243* Prev;
tfreecell21233* Freelist;
NI Free;
NI Acc;
NF64 Data;
};
struct tllchunk22004 {
NI Size;
NI Acc;
tllchunk22004* Next;
};
struct tbigchunk21245 {
  tbasechunk21241 Sup;
tbigchunk21245* Next;
tbigchunk21245* Prev;
NI Align;
NF64 Data;
};
struct ttrunk21214 {
ttrunk21214* Next;
NI Key;
TY21221 Bits;
};
typedef tavlnode22008* TY22014[2];
struct tavlnode22008 {
TY22014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tfreecell21233 {
tfreecell21233* Next;
NI Zerofield;
};
struct TY97013 {
  TGenericSeq Sup;
  NI64 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, errorassert_98074)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, setup_98089)(tnavmfrontend97004* ob, NIM_BOOL disasm, NI codesize);
N_NIMCALL(void, TMP812)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, init_91029)(tnavmbackend91004* ob, NI memsize);
N_NIMCALL(void, settraceofs_98116)(tnavmfrontend97004* ob, NI ofs);
N_NIMCALL(void, hiddenraiseassert_71220)(NimStringDesc* msg);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(E_Base*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell38449*, usrtocell_41843)(void* usr);
static N_INLINE(void, rtladdzct_43002)(tcell38449* c);
N_NOINLINE(void, addzct_41815)(tcellseq38465* s, tcell38449* c);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(NI, gettraceofs_98208)(tnavmfrontend97004* ob);
N_NIMCALL(void, setdisasmflag_98408)(tnavmfrontend97004* ob, NIM_BOOL flag);
N_NIMCALL(NIM_BOOL, getdisasmflag_98608)(tnavmfrontend97004* ob);
N_NIMCALL(void, addins_98808)(tnavmfrontend97004* ob, NU64* bundle, NU8 ins);
N_NIMCALL(void, pokebundle_99029)(tnavmfrontend97004* ob, NU64 bundle);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(void, pokeimm_99227)(tnavmfrontend97004* ob, NI64 imm);
N_NIMCALL(NU64, peekbundle_99424)(tnavmfrontend97004* ob, NI ofs);
N_NIMCALL(void, error_99606)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI64, peekimm_99623)(tnavmfrontend97004* ob, NI ofs);
N_NIMCALL(void, error_99806)(void);
N_NIMCALL(void, error_99822)(NimStringDesc* msg);
N_NIMCALL(void, compbundledrm_99838)(tnavmfrontend97004* ob);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, liimm_94197)(tnavmbackend91004* ob, NI64 val, NIM_BOOL dis);
N_NIMCALL(void, br_96529)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, eq_96668)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, gr_96703)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, le_96710)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, zr_96717)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, lx_94313)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, ld_94360)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, st_94397)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, lxi_94430)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, sxi_94524)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, lxd_94477)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, sxd_94571)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, add_94618)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, adc_94783)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, sub_94931)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, sbc_95079)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, slb_95227)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, srb_95394)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, anb_95544)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, gor_95692)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, xob_95840)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, dup_95988)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, swp_96030)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, ovr_96063)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, rot_96094)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, r_96578)(tnavmbackend91004* ob, NIM_BOOL dis);
N_NIMCALL(void, objectInit)(void* dest, TNimType* typ);
N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x, NI len);
N_NIMCALL(NimStringDesc*, nimInt64ToStr)(NI64 x);
N_NIMCALL(NimStringDesc*, HEX24_4201)(NU64 x);
N_NIMCALL(void, release_91253)(tnavmbackend91004* ob);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
static N_INLINE(void, writeln_91224)(FILE* f, NimStringDesc** x, NI xLen0);
N_NIMCALL(void, write_8862)(FILE* f, NimStringDesc* s);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, parseutilsInit)(void);
N_NOINLINE(void, parseutilsDatInit)(void);
N_NOINLINE(void, strutilsInit)(void);
N_NOINLINE(void, strutilsDatInit)(void);
N_NOINLINE(void, timesInit)(void);
N_NOINLINE(void, timesDatInit)(void);
N_NOINLINE(void, posixInit)(void);
N_NOINLINE(void, posixDatInit)(void);
N_NOINLINE(void, shmBufferInit)(void);
N_NOINLINE(void, shmBufferDatInit)(void);
N_NOINLINE(void, unsignedInit)(void);
N_NOINLINE(void, unsignedDatInit)(void);
N_NOINLINE(void, navmBackendInit)(void);
N_NOINLINE(void, navmBackendDatInit)(void);
N_NOINLINE(void, navmInstructionsInit)(void);
N_NOINLINE(void, navmInstructionsDatInit)(void);
N_NOINLINE(void, navmFrontendInit)(void);
N_NOINLINE(void, navmFrontendDatInit)(void);
STRING_LITERAL(TMP811, "[navmFrontend] ob.fInit[ofs] != true", 36);
STRING_LITERAL(TMP813, "not ob.fInit == false ", 22);
STRING_LITERAL(TMP821, "[peekBundle] ob.sVmMem[ofs] = NIL", 33);
STRING_LITERAL(TMP823, "[peekImm] ob.sVmMem[ofs] = NIL", 30);
STRING_LITERAL(TMP832, "[compBundleDRM] sys", 19);
STRING_LITERAL(TMP833, "[compBundleDRM] b", 17);
STRING_LITERAL(TMP834, "[compBundleDRM] bs", 18);
STRING_LITERAL(TMP835, "[compBundleDRM] pck", 19);
STRING_LITERAL(TMP836, "[compBundleDRM] unexpected error", 32);
STRING_LITERAL(TMP840, "bundle: ", 8);
STRING_LITERAL(TMP841, "sVmMem[0]: ", 11);
STRING_LITERAL(TMP842, "sVmMem[1]: ", 11);
STRING_LITERAL(TMP843, "sVmMem[2]: ", 11);
STRING_LITERAL(TMP844, "sVmMem[3]: ", 11);
STRING_LITERAL(TMP845, "first instruction: ", 19);
STRING_LITERAL(TMP846, "\012", 1);
extern TFrame* frameptr_11625;
extern TNimType NTI94008; /* tNavmSCell */
TNimType NTI97013; /* seq[tNavmSCell] */
extern TSafePoint* exchandler_11626;
extern TNimType NTI1049; /* EAssertionFailed */
extern E_Base* currexception_11628;
extern tgcheap40416 gch_40442;
extern TNimType NTI1049; /* EAssertionFailed */
extern TNimType NTI1049; /* EAssertionFailed */
extern TNimType NTI1049; /* EAssertionFailed */
extern TNimType NTI1049; /* EAssertionFailed */
extern TNimType NTI1049; /* EAssertionFailed */
extern TNimType NTI1049; /* EAssertionFailed */
extern TNimType NTI1049; /* EAssertionFailed */
extern TNimType NTI1049; /* EAssertionFailed */
extern TNimType NTI1049; /* EAssertionFailed */
tnavmfrontend97004 test_100561;
extern TNimType NTI91004; /* tNavmBackend */
TNimType NTI97004; /* tNavmFrontend */
extern TNimType NTI132; /* bool */
extern TNimType NTI94008; /* tNavmSCell */
extern TNimType NTI105; /* int */
NU64 bundle_100562;
NI trace_100563;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_11625;
	frameptr_11625 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_11625 = (*frameptr_11625).prev;
}

N_NIMCALL(void, errorassert_98074)(void) {
	TY94095 LOC1;
	nimfr("errorAssert", "navmFrontend.nim")
	nimln(289, "navmFrontend.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	nimln(289, "navmFrontend.nim");
	LOC1[0] = copyString(((NimStringDesc*) &TMP811));
	writeln_91224(stderr, LOC1, 1);
	nimln(290, "navmFrontend.nim");
	exit(0);
	popFrame();
}
N_NIMCALL(void, TMP812)(void* p, NI op) {
	TY97013* a;
	NI LOC1;
	a = (TY97013*)p;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

N_NIMCALL(void, setup_98089)(tnavmfrontend97004* ob, NIM_BOOL disasm, NI codesize) {
	nimfr("setup", "navmFrontend.nim")
	nimln(293, "navmFrontend.nim");
	(*ob).Fdisasm = disasm;
	nimln(294, "navmFrontend.nim");
	(*ob).Va = 0;
	nimln(295, "navmFrontend.nim");
	(*ob).Ovmmem = 0;
	nimln(297, "navmFrontend.nim");
	unsureAsgnRef((void**) &(*ob).Svmmem, (TY97013*) newSeq((&NTI97013), 0));
	nimln(298, "navmFrontend.nim");
	init_91029(&ob->Sup, codesize);
	popFrame();
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_11626;
	exchandler_11626 = s;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_11626 = (*exchandler_11626).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_11625 = s;
}

static N_INLINE(E_Base*, getCurrentException)(void) {
	E_Base* result;
	nimfr("getCurrentException", "system.nim")
	result = 0;
	nimln(2192, "system.nim");
	result = currexception_11628;
	popFrame();
	return result;
}

static N_INLINE(tcell38449*, usrtocell_41843)(void* usr) {
	tcell38449* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(106, "gc.nim");
	nimln(106, "gc.nim");
	nimln(106, "gc.nim");
	result = ((tcell38449*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38449))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_43002)(tcell38449* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(184, "gc.nim");
	addzct_41815(&gch_40442.Zct, c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(236, "gc.nim");
	nimln(696, "system.nim");
	nimln(696, "system.nim");
	if (!!((src == NIM_NIL))) goto LA2;
	{
		tcell38449* c;
		nimln(237, "gc.nim");
		c = usrtocell_41843(src);
		nimln(157, "gc.nim");
		(*c).Refcount += 8;
	}
	LA2: ;
	nimln(239, "gc.nim");
	nimln(696, "system.nim");
	nimln(696, "system.nim");
	if (!!(((*dest) == NIM_NIL))) goto LA6;
	{
		tcell38449* c;
		nimln(240, "gc.nim");
		c = usrtocell_41843((*dest));
		nimln(241, "gc.nim");
		nimln(155, "gc.nim");
		(*c).Refcount -= 8;
		nimln(156, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA10;
		{
			nimln(242, "gc.nim");
			rtladdzct_43002(c);
		}
		LA10: ;
	}
	LA6: ;
	nimln(243, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRefNoCycle((void**) &currexception_11628, (*currexception_11628).parent);
}

N_NIMCALL(void, settraceofs_98116)(tnavmfrontend97004* ob, NI ofs) {
	TSafePoint TMP814;
	nimfr("setTraceOfs", "navmFrontend.nim")
	nimln(301, "navmFrontend.nim");
	nimln(301, "navmFrontend.nim");
	nimln(301, "navmFrontend.nim");
	nimln(301, "navmFrontend.nim");
	if (!!(!(((*ob).Sup.Finit == NIM_FALSE)))) goto LA2;
	{
		nimln(301, "navmFrontend.nim");
		hiddenraiseassert_71220(((NimStringDesc*) &TMP813));
	}
	LA2: ;
	nimln(303, "navmFrontend.nim");
	pushSafePoint(&TMP814);
	TMP814.status = setjmp(TMP814.context);
	if (TMP814.status == 0) {
		nimln(304, "navmFrontend.nim");
		(*ob).Ovmmem = ofs;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&F);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI1049))) {
			TMP814.status = 0;
			nimln(306, "navmFrontend.nim");
			errorassert_98074();
			popCurrentException();
		}
	}
	if (TMP814.status != 0) reraiseException();
	popFrame();
}

N_NIMCALL(NI, gettraceofs_98208)(tnavmfrontend97004* ob) {
	NI result;
	TSafePoint TMP815;
	nimfr("getTraceOfs", "navmFrontend.nim")
	result = 0;
	nimln(309, "navmFrontend.nim");
	nimln(309, "navmFrontend.nim");
	nimln(309, "navmFrontend.nim");
	nimln(309, "navmFrontend.nim");
	if (!!(!(((*ob).Sup.Finit == NIM_FALSE)))) goto LA2;
	{
		nimln(309, "navmFrontend.nim");
		hiddenraiseassert_71220(((NimStringDesc*) &TMP813));
	}
	LA2: ;
	nimln(311, "navmFrontend.nim");
	pushSafePoint(&TMP815);
	TMP815.status = setjmp(TMP815.context);
	if (TMP815.status == 0) {
		nimln(311, "navmFrontend.nim");
		result = (*ob).Ovmmem;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&F);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI1049))) {
			TMP815.status = 0;
			nimln(312, "navmFrontend.nim");
			errorassert_98074();
			popCurrentException();
		}
	}
	if (TMP815.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(void, setdisasmflag_98408)(tnavmfrontend97004* ob, NIM_BOOL flag) {
	TSafePoint TMP816;
	nimfr("setDisAsmFlag", "navmFrontend.nim")
	nimln(315, "navmFrontend.nim");
	nimln(315, "navmFrontend.nim");
	nimln(315, "navmFrontend.nim");
	nimln(315, "navmFrontend.nim");
	if (!!(!(((*ob).Sup.Finit == NIM_FALSE)))) goto LA2;
	{
		nimln(315, "navmFrontend.nim");
		hiddenraiseassert_71220(((NimStringDesc*) &TMP813));
	}
	LA2: ;
	nimln(317, "navmFrontend.nim");
	pushSafePoint(&TMP816);
	TMP816.status = setjmp(TMP816.context);
	if (TMP816.status == 0) {
		nimln(317, "navmFrontend.nim");
		(*ob).Fdisasm = flag;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&F);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI1049))) {
			TMP816.status = 0;
			nimln(318, "navmFrontend.nim");
			errorassert_98074();
			popCurrentException();
		}
	}
	if (TMP816.status != 0) reraiseException();
	popFrame();
}

N_NIMCALL(NIM_BOOL, getdisasmflag_98608)(tnavmfrontend97004* ob) {
	NIM_BOOL result;
	TSafePoint TMP817;
	nimfr("getDisAsmFlag", "navmFrontend.nim")
	result = 0;
	nimln(321, "navmFrontend.nim");
	nimln(321, "navmFrontend.nim");
	nimln(321, "navmFrontend.nim");
	nimln(321, "navmFrontend.nim");
	if (!!(!(((*ob).Sup.Finit == NIM_FALSE)))) goto LA2;
	{
		nimln(321, "navmFrontend.nim");
		hiddenraiseassert_71220(((NimStringDesc*) &TMP813));
	}
	LA2: ;
	nimln(323, "navmFrontend.nim");
	pushSafePoint(&TMP817);
	TMP817.status = setjmp(TMP817.context);
	if (TMP817.status == 0) {
		nimln(323, "navmFrontend.nim");
		result = (*ob).Fdisasm;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&F);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI1049))) {
			TMP817.status = 0;
			nimln(324, "navmFrontend.nim");
			errorassert_98074();
			popCurrentException();
		}
	}
	if (TMP817.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(void, addins_98808)(tnavmfrontend97004* ob, NU64* bundle, NU8 ins) {
	NI bgslot;
	TSafePoint TMP818;
	nimfr("addIns", "navmFrontend.nim")
	nimln(327, "navmFrontend.nim");
	nimln(327, "navmFrontend.nim");
	nimln(327, "navmFrontend.nim");
	nimln(327, "navmFrontend.nim");
	if (!!(!(((*ob).Sup.Finit == NIM_FALSE)))) goto LA2;
	{
		nimln(327, "navmFrontend.nim");
		hiddenraiseassert_71220(((NimStringDesc*) &TMP813));
	}
	LA2: ;
	nimln(328, "navmFrontend.nim");
	nimln(328, "navmFrontend.nim");
	bgslot = ins;
	nimln(330, "navmFrontend.nim");
	pushSafePoint(&TMP818);
	TMP818.status = setjmp(TMP818.context);
	if (TMP818.status == 0) {
		nimln(331, "navmFrontend.nim");
		nimln(331, "navmFrontend.nim");
		(*bundle) = (NU64)((NU64)((*bundle)) << (NU64)(((NU64) 5)));
		nimln(332, "navmFrontend.nim");
		nimln(332, "navmFrontend.nim");
		(*bundle) = (NU64)((NU64)((*bundle)) + (NU64)(((NU64) (bgslot))));
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&F);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI1049))) {
			TMP818.status = 0;
			nimln(334, "navmFrontend.nim");
			errorassert_98074();
			popCurrentException();
		}
	}
	if (TMP818.status != 0) reraiseException();
	popFrame();
}

N_NIMCALL(void, pokebundle_99029)(tnavmfrontend97004* ob, NU64 bundle) {
	TSafePoint TMP819;
	nimfr("pokeBundle", "navmFrontend.nim")
	nimln(337, "navmFrontend.nim");
	nimln(337, "navmFrontend.nim");
	nimln(337, "navmFrontend.nim");
	nimln(337, "navmFrontend.nim");
	if (!!(!(((*ob).Sup.Finit == NIM_FALSE)))) goto LA2;
	{
		nimln(337, "navmFrontend.nim");
		hiddenraiseassert_71220(((NimStringDesc*) &TMP813));
	}
	LA2: ;
	nimln(339, "navmFrontend.nim");
	pushSafePoint(&TMP819);
	TMP819.status = setjmp(TMP819.context);
	if (TMP819.status == 0) {
		NI64 volatile b;
		nimln(340, "navmFrontend.nim");
		b = ((NI64) (bundle));
		nimln(341, "navmFrontend.nim");
		(*ob).Svmmem = (TY97013*) incrSeq(&((*ob).Svmmem)->Sup, sizeof(NI64));
		(*ob).Svmmem->data[(*ob).Svmmem->Sup.len-1] = b;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&F);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI1049))) {
			TMP819.status = 0;
			nimln(343, "navmFrontend.nim");
			errorassert_98074();
			popCurrentException();
		}
	}
	if (TMP819.status != 0) reraiseException();
	popFrame();
}

N_NIMCALL(void, pokeimm_99227)(tnavmfrontend97004* ob, NI64 imm) {
	TSafePoint TMP820;
	nimfr("pokeImm", "navmFrontend.nim")
	nimln(346, "navmFrontend.nim");
	nimln(346, "navmFrontend.nim");
	nimln(346, "navmFrontend.nim");
	nimln(346, "navmFrontend.nim");
	if (!!(!(((*ob).Sup.Finit == NIM_FALSE)))) goto LA2;
	{
		nimln(346, "navmFrontend.nim");
		hiddenraiseassert_71220(((NimStringDesc*) &TMP813));
	}
	LA2: ;
	nimln(348, "navmFrontend.nim");
	pushSafePoint(&TMP820);
	TMP820.status = setjmp(TMP820.context);
	if (TMP820.status == 0) {
		nimln(348, "navmFrontend.nim");
		(*ob).Svmmem = (TY97013*) incrSeq(&((*ob).Svmmem)->Sup, sizeof(NI64));
		(*ob).Svmmem->data[(*ob).Svmmem->Sup.len-1] = imm;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&F);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI1049))) {
			TMP820.status = 0;
			nimln(349, "navmFrontend.nim");
			errorassert_98074();
			popCurrentException();
		}
	}
	if (TMP820.status != 0) reraiseException();
	popFrame();
}

N_NIMCALL(void, error_99606)(void) {
	TY94095 LOC1;
	nimfr("error", "navmFrontend.nim")
	nimln(355, "navmFrontend.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	nimln(355, "navmFrontend.nim");
	LOC1[0] = copyString(((NimStringDesc*) &TMP821));
	writeln_91224(stderr, LOC1, 1);
	nimln(356, "navmFrontend.nim");
	exit(0);
	popFrame();
}

N_NIMCALL(NU64, peekbundle_99424)(tnavmfrontend97004* ob, NI ofs) {
	NU64 result;
	TSafePoint TMP822;
	nimfr("peekBundle", "navmFrontend.nim")
	result = 0;
	nimln(352, "navmFrontend.nim");
	nimln(352, "navmFrontend.nim");
	nimln(352, "navmFrontend.nim");
	nimln(352, "navmFrontend.nim");
	if (!!(!(((*ob).Sup.Finit == NIM_FALSE)))) goto LA2;
	{
		nimln(352, "navmFrontend.nim");
		hiddenraiseassert_71220(((NimStringDesc*) &TMP813));
	}
	LA2: ;
	nimln(358, "navmFrontend.nim");
	pushSafePoint(&TMP822);
	TMP822.status = setjmp(TMP822.context);
	if (TMP822.status == 0) {
		nimln(358, "navmFrontend.nim");
		if ((NU)(ofs) >= (NU)((*ob).Svmmem->Sup.len)) raiseIndexError();
		result = ((NU64) ((*ob).Svmmem->data[ofs]));
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&F);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI1049))) {
			TMP822.status = 0;
			nimln(359, "navmFrontend.nim");
			errorassert_98074();
			popCurrentException();
		}
		else		{
			TMP822.status = 0;
			nimln(360, "navmFrontend.nim");
			error_99606();
			popCurrentException();
		}
	}
	if (TMP822.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(void, error_99806)(void) {
	TY94095 LOC1;
	nimfr("error", "navmFrontend.nim")
	nimln(366, "navmFrontend.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	nimln(366, "navmFrontend.nim");
	LOC1[0] = copyString(((NimStringDesc*) &TMP823));
	writeln_91224(stderr, LOC1, 1);
	nimln(367, "navmFrontend.nim");
	exit(0);
	popFrame();
}

N_NIMCALL(NI64, peekimm_99623)(tnavmfrontend97004* ob, NI ofs) {
	NI64 result;
	TSafePoint TMP824;
	nimfr("peekImm", "navmFrontend.nim")
	result = 0;
	nimln(363, "navmFrontend.nim");
	nimln(363, "navmFrontend.nim");
	nimln(363, "navmFrontend.nim");
	nimln(363, "navmFrontend.nim");
	if (!!(!(((*ob).Sup.Finit == NIM_FALSE)))) goto LA2;
	{
		nimln(363, "navmFrontend.nim");
		hiddenraiseassert_71220(((NimStringDesc*) &TMP813));
	}
	LA2: ;
	nimln(369, "navmFrontend.nim");
	pushSafePoint(&TMP824);
	TMP824.status = setjmp(TMP824.context);
	if (TMP824.status == 0) {
		nimln(369, "navmFrontend.nim");
		if ((NU)(ofs) >= (NU)((*ob).Svmmem->Sup.len)) raiseIndexError();
		result = (*ob).Svmmem->data[ofs];
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&F);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI1049))) {
			TMP824.status = 0;
			nimln(370, "navmFrontend.nim");
			errorassert_98074();
			popCurrentException();
		}
		else		{
			TMP824.status = 0;
			nimln(371, "navmFrontend.nim");
			error_99806();
			popCurrentException();
		}
	}
	if (TMP824.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(void, error_99822)(NimStringDesc* msg) {
	TY94095 LOC1;
	nimfr("error", "navmFrontend.nim")
	nimln(374, "navmFrontend.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	nimln(374, "navmFrontend.nim");
	LOC1[0] = copyString(msg);
	writeln_91224(stderr, LOC1, 1);
	nimln(375, "navmFrontend.nim");
	exit(0);
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	NIM_BOOL LOC2;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	LOC2 = (0 <= (NI)(result ^ a));
	if (LOC2) goto LA3;
	LOC2 = (0 <= (NI)(result ^ b));
	LA3: ;
	if (!LOC2) goto LA4;
	{
		goto BeforeRet;
	}
	LA4: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, compbundledrm_99838)(tnavmfrontend97004* ob) {
	NU64 vbndl;
	NI8 vinsa;
	NI8 vinsb;
	NI i;
	TSafePoint TMP825;
	nimfr("compBundleDRM", "navmFrontend.nim")
	nimln(379, "navmFrontend.nim");
	if ((NU)((*ob).Ovmmem) >= (NU)((*ob).Svmmem->Sup.len)) raiseIndexError();
	vbndl = ((NU64) ((*ob).Svmmem->data[(*ob).Ovmmem]));
	nimln(380, "navmFrontend.nim");
	vinsa = ((NI8) 0);
	nimln(381, "navmFrontend.nim");
	vinsb = ((NI8) 0);
	nimln(382, "navmFrontend.nim");
	i = 1;
	nimln(384, "navmFrontend.nim");
	nimln(384, "navmFrontend.nim");
	nimln(384, "navmFrontend.nim");
	nimln(384, "navmFrontend.nim");
	if (!!(!(((*ob).Sup.Finit == NIM_FALSE)))) goto LA2;
	{
		nimln(384, "navmFrontend.nim");
		hiddenraiseassert_71220(((NimStringDesc*) &TMP813));
	}
	LA2: ;
	nimln(386, "navmFrontend.nim");
	pushSafePoint(&TMP825);
	TMP825.status = setjmp(TMP825.context);
	if (TMP825.status == 0) {
		NI TMP826;
		nimln(387, "navmFrontend.nim");
		nimln(387, "navmFrontend.nim");
		TMP826 = addInt((*ob).Ovmmem, 1);
		(*ob).Ovmmem = (NI64)(TMP826);
		{
			nimln(399, "navmFrontend.nim");
			while (1) {
				nimln(399, "navmFrontend.nim");
				if (!(i <= 12)) goto LA7;
				nimln(400, "navmFrontend.nim");
				nimln(400, "navmFrontend.nim");
				vinsa = ((NI8) ((NU64)(vbndl & ((NU64) 31))));
				nimln(401, "navmFrontend.nim");
				nimln(401, "navmFrontend.nim");
				nimln(401, "navmFrontend.nim");
				vinsb = ((NI8) ((NU64)((NU64)((NU64)(vbndl) >> (NU64)(((NU64) 5))) & ((NU64) 31))));
				nimln(402, "navmFrontend.nim");
				nimln(402, "navmFrontend.nim");
				vbndl = (NU64)((NU64)(vbndl) >> (NU64)(((NU64) 5)));
				nimln(404, "navmFrontend.nim");
				switch (vinsa) {
				case ((NI8) 1):
				{
					NI TMP827;
					nimln(406, "navmFrontend.nim");
					if ((NU)((*ob).Ovmmem) >= (NU)((*ob).Svmmem->Sup.len)) raiseIndexError();
					liimm_94197(&ob->Sup, (*ob).Svmmem->data[(*ob).Ovmmem], (*ob).Fdisasm);
					nimln(407, "navmFrontend.nim");
					nimln(407, "navmFrontend.nim");
					TMP827 = addInt((*ob).Ovmmem, 1);
					(*ob).Ovmmem = (NI64)(TMP827);
				}
				break;
				case ((NI8) 26):
				{
					nimln(409, "navmFrontend.nim");
					br_96529(&ob->Sup, (*ob).Fdisasm);
					nimln(410, "navmFrontend.nim");
					goto LA6;
				}
				break;
				case ((NI8) 28):
				{
					NIM_BOOL LOC12;
					nimln(412, "navmFrontend.nim");
					eq_96668(&ob->Sup, (*ob).Fdisasm);
					nimln(413, "navmFrontend.nim");
					nimln(413, "navmFrontend.nim");
					LOC12 = NIM_TRUE;
					if (!(LOC12)) goto LA13;
					nimln(704, "system.nim");
					LOC12 = (((NI8) 27) < vinsb);
					LA13: ;
					if (!LOC12) goto LA14;
					{
						NI TMP828;
						nimln(414, "navmFrontend.nim");
						nimln(414, "navmFrontend.nim");
						vbndl = (NU64)((NU64)(vbndl) >> (NU64)(((NU64) 5)));
						nimln(415, "navmFrontend.nim");
						nimln(415, "navmFrontend.nim");
						TMP828 = addInt(i, 1);
						i = (NI64)(TMP828);
					}
					LA14: ;
				}
				break;
				case ((NI8) 29):
				{
					NIM_BOOL LOC19;
					nimln(417, "navmFrontend.nim");
					gr_96703(&ob->Sup, (*ob).Fdisasm);
					nimln(418, "navmFrontend.nim");
					nimln(418, "navmFrontend.nim");
					LOC19 = NIM_TRUE;
					if (!(LOC19)) goto LA20;
					nimln(704, "system.nim");
					LOC19 = (((NI8) 27) < vinsb);
					LA20: ;
					if (!LOC19) goto LA21;
					{
						NI TMP829;
						nimln(419, "navmFrontend.nim");
						nimln(419, "navmFrontend.nim");
						vbndl = (NU64)((NU64)(vbndl) >> (NU64)(((NU64) 5)));
						nimln(420, "navmFrontend.nim");
						nimln(420, "navmFrontend.nim");
						TMP829 = addInt(i, 1);
						i = (NI64)(TMP829);
					}
					LA21: ;
				}
				break;
				case ((NI8) 30):
				{
					NIM_BOOL LOC26;
					nimln(422, "navmFrontend.nim");
					le_96710(&ob->Sup, (*ob).Fdisasm);
					nimln(423, "navmFrontend.nim");
					nimln(423, "navmFrontend.nim");
					LOC26 = NIM_TRUE;
					if (!(LOC26)) goto LA27;
					nimln(704, "system.nim");
					LOC26 = (((NI8) 27) < vinsb);
					LA27: ;
					if (!LOC26) goto LA28;
					{
						NI TMP830;
						nimln(424, "navmFrontend.nim");
						nimln(424, "navmFrontend.nim");
						vbndl = (NU64)((NU64)(vbndl) >> (NU64)(((NU64) 5)));
						nimln(425, "navmFrontend.nim");
						nimln(425, "navmFrontend.nim");
						TMP830 = addInt(i, 1);
						i = (NI64)(TMP830);
					}
					LA28: ;
				}
				break;
				case ((NI8) 31):
				{
					NIM_BOOL LOC33;
					nimln(427, "navmFrontend.nim");
					zr_96717(&ob->Sup, (*ob).Fdisasm);
					nimln(428, "navmFrontend.nim");
					nimln(428, "navmFrontend.nim");
					LOC33 = NIM_TRUE;
					if (!(LOC33)) goto LA34;
					nimln(704, "system.nim");
					LOC33 = (((NI8) 27) < vinsb);
					LA34: ;
					if (!LOC33) goto LA35;
					{
						NI TMP831;
						nimln(429, "navmFrontend.nim");
						nimln(429, "navmFrontend.nim");
						vbndl = (NU64)((NU64)(vbndl) >> (NU64)(((NU64) 5)));
						nimln(430, "navmFrontend.nim");
						nimln(430, "navmFrontend.nim");
						TMP831 = addInt(i, 1);
						i = (NI64)(TMP831);
					}
					LA35: ;
				}
				break;
				case ((NI8) 0):
				{
					nimln(431, "navmFrontend.nim");
					error_99822(((NimStringDesc*) &TMP832));
				}
				break;
				case ((NI8) 24):
				{
					nimln(432, "navmFrontend.nim");
					error_99822(((NimStringDesc*) &TMP833));
				}
				break;
				case ((NI8) 25):
				{
					nimln(433, "navmFrontend.nim");
					error_99822(((NimStringDesc*) &TMP834));
				}
				break;
				case ((NI8) 22):
				{
					nimln(434, "navmFrontend.nim");
					error_99822(((NimStringDesc*) &TMP835));
				}
				break;
				case ((NI8) 2):
				{
					nimln(435, "navmFrontend.nim");
					lx_94313(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 3):
				{
					nimln(436, "navmFrontend.nim");
					ld_94360(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 4):
				{
					nimln(437, "navmFrontend.nim");
					st_94397(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 5):
				{
					nimln(438, "navmFrontend.nim");
					lxi_94430(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 6):
				{
					nimln(439, "navmFrontend.nim");
					sxi_94524(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 7):
				{
					nimln(440, "navmFrontend.nim");
					lxd_94477(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 8):
				{
					nimln(441, "navmFrontend.nim");
					sxd_94571(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 9):
				{
					nimln(442, "navmFrontend.nim");
					add_94618(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 10):
				{
					nimln(443, "navmFrontend.nim");
					adc_94783(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 11):
				{
					nimln(444, "navmFrontend.nim");
					sub_94931(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 12):
				{
					nimln(445, "navmFrontend.nim");
					sbc_95079(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 13):
				{
					nimln(446, "navmFrontend.nim");
					slb_95227(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 14):
				{
					nimln(447, "navmFrontend.nim");
					srb_95394(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 15):
				{
					nimln(448, "navmFrontend.nim");
					anb_95544(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 16):
				{
					nimln(449, "navmFrontend.nim");
					gor_95692(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 17):
				{
					nimln(450, "navmFrontend.nim");
					xob_95840(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 18):
				{
					nimln(451, "navmFrontend.nim");
					dup_95988(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 20):
				{
					nimln(452, "navmFrontend.nim");
					swp_96030(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 21):
				{
					nimln(453, "navmFrontend.nim");
					ovr_96063(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 23):
				{
					nimln(454, "navmFrontend.nim");
					rot_96094(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 27):
				{
					nimln(455, "navmFrontend.nim");
					r_96578(&ob->Sup, (*ob).Fdisasm);
				}
				break;
				case ((NI8) 19):
				{
					nimln(456, "navmFrontend.nim");
					i = i;
				}
				break;
				default:
				{
					nimln(457, "navmFrontend.nim");
					error_99822(((NimStringDesc*) &TMP836));
				}
				break;
				}
			} LA7: ;
		} LA6: ;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&F);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI1049))) {
			TMP825.status = 0;
			nimln(459, "navmFrontend.nim");
			errorassert_98074();
			popCurrentException();
		}
	}
	if (TMP825.status != 0) reraiseException();
	popFrame();
}

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);
}
int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	systemDatInit();
	parseutilsDatInit();
	strutilsDatInit();
	timesDatInit();
	posixDatInit();
	shmBufferDatInit();
	unsignedDatInit();
	navmBackendDatInit();
	navmInstructionsDatInit();
	navmFrontendDatInit();
	initStackBottom();
	systemInit();
	parseutilsInit();
	strutilsInit();
	timesInit();
	posixInit();
	shmBufferInit();
	unsignedInit();
	navmBackendInit();
	navmInstructionsInit();
	navmFrontendInit();
}
int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

static N_INLINE(void, writeln_91224)(FILE* f, NimStringDesc** x, NI xLen0) {
	NimStringDesc* i_91238;
	NI i_91240;
	nimfr("writeln", "sysio.nim")
	i_91238 = 0;
	nimln(1343, "system.nim");
	i_91240 = 0;
	nimln(1344, "system.nim");
	while (1) {
		nimln(1344, "system.nim");
		nimln(1344, "system.nim");
		if (!(i_91240 < xLen0)) goto LA1;
		nimln(1345, "system.nim");
		i_91238 = x[i_91240];
		nimln(159, "sysio.nim");
		write_8862(f, i_91238);
		nimln(1346, "system.nim");
		i_91240 += 1;
	} LA1: ;
	nimln(160, "sysio.nim");
	write_8862(f, ((NimStringDesc*) &TMP846));
	popFrame();
}
N_NOINLINE(void, navmFrontendInit)(void) {
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	NimStringDesc* LOC6;
	nimfr("navmFrontend", "navmFrontend.nim")
	objectInit(&test_100561, (&NTI97004));
	nimln(468, "navmFrontend.nim");
	setup_98089(&test_100561, NIM_TRUE, 65535);
	nimln(470, "navmFrontend.nim");
	trace_100563 = gettraceofs_98208(&test_100561);
	nimln(472, "navmFrontend.nim");
	addins_98808(&test_100561, &bundle_100562, ((NU8) 26));
	nimln(473, "navmFrontend.nim");
	addins_98808(&test_100561, &bundle_100562, ((NU8) 9));
	nimln(474, "navmFrontend.nim");
	addins_98808(&test_100561, &bundle_100562, ((NU8) 1));
	nimln(475, "navmFrontend.nim");
	addins_98808(&test_100561, &bundle_100562, ((NU8) 11));
	nimln(476, "navmFrontend.nim");
	addins_98808(&test_100561, &bundle_100562, ((NU8) 1));
	nimln(477, "navmFrontend.nim");
	addins_98808(&test_100561, &bundle_100562, ((NU8) 1));
	nimln(478, "navmFrontend.nim");
	nimln(478, "navmFrontend.nim");
	LOC1 = 0;
	LOC1 = nsuToHex(((NI64) (bundle_100562)), 16);
	printf("%s%s\012", (((NimStringDesc*) &TMP840))->data, (LOC1)->data);
	nimln(480, "navmFrontend.nim");
	pokebundle_99029(&test_100561, bundle_100562);
	nimln(481, "navmFrontend.nim");
	pokeimm_99227(&test_100561, 100);
	nimln(482, "navmFrontend.nim");
	pokeimm_99227(&test_100561, 200);
	nimln(483, "navmFrontend.nim");
	pokeimm_99227(&test_100561, 300);
	nimln(484, "navmFrontend.nim");
	nimln(484, "navmFrontend.nim");
	if ((NU)(0) >= (NU)(test_100561.Svmmem->Sup.len)) raiseIndexError();
	LOC2 = 0;
	LOC2 = nsuToHex(((NI64) (test_100561.Svmmem->data[0])), 16);
	printf("%s%s\012", (((NimStringDesc*) &TMP841))->data, (LOC2)->data);
	nimln(485, "navmFrontend.nim");
	nimln(485, "navmFrontend.nim");
	if ((NU)(1) >= (NU)(test_100561.Svmmem->Sup.len)) raiseIndexError();
	LOC3 = 0;
	LOC3 = nimInt64ToStr(test_100561.Svmmem->data[1]);
	printf("%s%s\012", (((NimStringDesc*) &TMP842))->data, (LOC3)->data);
	nimln(486, "navmFrontend.nim");
	nimln(486, "navmFrontend.nim");
	if ((NU)(2) >= (NU)(test_100561.Svmmem->Sup.len)) raiseIndexError();
	LOC4 = 0;
	LOC4 = nimInt64ToStr(test_100561.Svmmem->data[2]);
	printf("%s%s\012", (((NimStringDesc*) &TMP843))->data, (LOC4)->data);
	nimln(487, "navmFrontend.nim");
	nimln(487, "navmFrontend.nim");
	if ((NU)(2) >= (NU)(test_100561.Svmmem->Sup.len)) raiseIndexError();
	LOC5 = 0;
	LOC5 = nimInt64ToStr(test_100561.Svmmem->data[2]);
	printf("%s%s\012", (((NimStringDesc*) &TMP844))->data, (LOC5)->data);
	nimln(489, "navmFrontend.nim");
	nimln(489, "navmFrontend.nim");
	nimln(489, "navmFrontend.nim");
	LOC6 = 0;
	LOC6 = HEX24_4201(((NU64) ((NU64)(bundle_100562 & ((NU64) 31)))));
	printf("%s%s\012", (((NimStringDesc*) &TMP845))->data, (LOC6)->data);
	nimln(491, "navmFrontend.nim");
	compbundledrm_99838(&test_100561);
	nimln(493, "navmFrontend.nim");
	release_91253(&test_100561.Sup);
	popFrame();
}

N_NOINLINE(void, navmFrontendDatInit)(void) {
static TNimNode* TMP839[4];
static TNimNode TMP119[5];
NTI97013.size = sizeof(TY97013*);
NTI97013.kind = 24;
NTI97013.base = (&NTI94008);
NTI97013.flags = 2;
NTI97013.marker = TMP812;
NTI97004.size = sizeof(tnavmfrontend97004);
NTI97004.kind = 17;
NTI97004.base = (&NTI91004);
NTI97004.flags = 2;
TMP839[0] = &TMP119[1];
TMP119[1].kind = 1;
TMP119[1].offset = offsetof(tnavmfrontend97004, Fdisasm);
TMP119[1].typ = (&NTI132);
TMP119[1].name = "fDisAsm";
TMP839[1] = &TMP119[2];
TMP119[2].kind = 1;
TMP119[2].offset = offsetof(tnavmfrontend97004, Va);
TMP119[2].typ = (&NTI94008);
TMP119[2].name = "vA";
TMP839[2] = &TMP119[3];
TMP119[3].kind = 1;
TMP119[3].offset = offsetof(tnavmfrontend97004, Svmmem);
TMP119[3].typ = (&NTI97013);
TMP119[3].name = "sVmMem";
TMP839[3] = &TMP119[4];
TMP119[4].kind = 1;
TMP119[4].offset = offsetof(tnavmfrontend97004, Ovmmem);
TMP119[4].typ = (&NTI105);
TMP119[4].name = "oVmMem";
TMP119[0].len = 4; TMP119[0].kind = 2; TMP119[0].sons = &TMP839[0];
NTI97004.node = &TMP119[0];
}

